-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- The calcChargenStats event triggers when the stats review menu is shown.
--- 	
--- 	The player stats will have already been calculated, but on this event you may modify them before the menu is displayed.
--- @class calcChargenStatsEventData
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
