-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- The simulated event occurs after almost all game logic, excluding when the game is paused or in menu mode. This event is intended to allow changes to the scene that will not be overwritten by game logic.
--- @class simulatedEventData
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
