#pragma once

namespace se::cs::dialog::edit_creature_object_window {

	constexpr UINT DIALOG_ID = 152;

	// Default IDs.
	constexpr UINT CONTROL_ID_ADD_ANIMATION_FILE_BUTTON = 1043;
	constexpr UINT CONTROL_ID_AGI_EDIT = 1603;
	constexpr UINT CONTROL_ID_AI_BUTTON = 1205;
	constexpr UINT CONTROL_ID_ANIMATION_BUTTON = 1206;
	constexpr UINT CONTROL_ID_ATTACK1_MAX_EDIT = 1202;
	constexpr UINT CONTROL_ID_ATTACK1_MIN_EDIT = 1199;
	constexpr UINT CONTROL_ID_ATTACK2_MAX_EDIT = 1203;
	constexpr UINT CONTROL_ID_ATTACK2_MIN_EDIT = 1200;
	constexpr UINT CONTROL_ID_ATTACK3_MAX_EDIT = 1204;
	constexpr UINT CONTROL_ID_ATTACK3_MIN_EDIT = 1201;
	constexpr UINT CONTROL_ID_BIPED_BUTTON = 1007;
	constexpr UINT CONTROL_ID_BLOCKED_BUTTON = 1684;
	constexpr UINT CONTROL_ID_BLOOD_COMBO = 1170;
	constexpr UINT CONTROL_ID_CANCEL_BUTTON = 2;
	constexpr UINT CONTROL_ID_COMBAT_EDIT = 1046;
	constexpr UINT CONTROL_ID_CORPSES_PERSIST_BUTTON = 1683;
	constexpr UINT CONTROL_ID_DETAILS_LIST = 1018;
	constexpr UINT CONTROL_ID_DETAILS_TABS = 1111;
	constexpr UINT CONTROL_ID_DIALOGUE_BUTTON = 1207;
	constexpr UINT CONTROL_ID_ENCUMBRANCE_STATIC = 1182;
	constexpr UINT CONTROL_ID_END_EDIT = 1605;
	constexpr UINT CONTROL_ID_ESSENTIAL_BUTTON = 1180;
	constexpr UINT CONTROL_ID_FATIGUE_EDIT = 1179;
	constexpr UINT CONTROL_ID_FLIES_BUTTON = 1218;
	constexpr UINT CONTROL_ID_HEALTH_EDIT = 1024;
	constexpr UINT CONTROL_ID_ID_EDIT = 1028;
	constexpr UINT CONTROL_ID_INT_EDIT = 1601;
	constexpr UINT CONTROL_ID_LEVEL_EDIT = 1063;
	constexpr UINT CONTROL_ID_LUC_EDIT = 1607;
	constexpr UINT CONTROL_ID_MAGIC_EDIT = 1047;
	constexpr UINT CONTROL_ID_MAGICKA_EDIT = 1178;
	constexpr UINT CONTROL_ID_NAME_EDIT = 1060;
	constexpr UINT CONTROL_ID_NONE_BUTTON = 1221;
	constexpr UINT CONTROL_ID_OK_BUTTON = 1;
	constexpr UINT CONTROL_ID_PER_EDIT = 1606;
	constexpr UINT CONTROL_ID_RESPAWN_BUTTON = 1216;
	constexpr UINT CONTROL_ID_SCALE_EDIT = 1025;
	constexpr UINT CONTROL_ID_SCRIPT_COMBO = 1226;
	constexpr UINT CONTROL_ID_SCRIPT_EDIT_BUTTON = 1062;
	constexpr UINT CONTROL_ID_SOUL_EDIT = 1197;
	constexpr UINT CONTROL_ID_SOUND_GEN_COMBO = 1171;
	constexpr UINT CONTROL_ID_SPD_EDIT = 1604;
	constexpr UINT CONTROL_ID_STEALTH_EDIT = 1048;
	constexpr UINT CONTROL_ID_STR_EDIT = 1600;
	constexpr UINT CONTROL_ID_SWIMS_BUTTON = 1217;
	constexpr UINT CONTROL_ID_TYPE_COMBO = 1050;
	constexpr UINT CONTROL_ID_WALKS_BUTTON = 1219;
	constexpr UINT CONTROL_ID_WEAPON_AND_SHIELD_BUTTON = 1008;
	constexpr UINT CONTROL_ID_WIL_EDIT = 1602;

	void installPatches();
}
