#pragma once

namespace se::cs::dialog::edit_alchemy_object_window {

	constexpr UINT DIALOG_ID = 165;

	// Default IDs.
	constexpr UINT CONTROL_ID_ADD_ART_FILE_BUTTON = 1043;
	constexpr UINT CONTROL_ID_AUTO_CALCULATE_VALUE_BUTTON = 1215;
	constexpr UINT CONTROL_ID_BLOCKED_BUTTON = 1684;
	constexpr UINT CONTROL_ID_CANCEL_BUTTON = 2;
	constexpr UINT CONTROL_ID_EFFECT1_COST_STATIC = 1300;
	constexpr UINT CONTROL_ID_EFFECT1_DURATION_EDIT = 1263;
	constexpr UINT CONTROL_ID_EFFECT1_EFFECT_COMBO = 1365;
	constexpr UINT CONTROL_ID_EFFECT1_EFFECT_VAR_COMBO = 1624;
	constexpr UINT CONTROL_ID_EFFECT1_MAGNITUDE_EDIT = 1391;
	constexpr UINT CONTROL_ID_EFFECT1_TOTAL_COST_STATIC = 1287;
	constexpr UINT CONTROL_ID_EFFECT2_COST_STATIC = 1301;
	constexpr UINT CONTROL_ID_EFFECT2_DURATION_EDIT = 1264;
	constexpr UINT CONTROL_ID_EFFECT2_EFFECT_COMBO = 1366;
	constexpr UINT CONTROL_ID_EFFECT2_EFFECT_VAR_COMBO = 1625;
	constexpr UINT CONTROL_ID_EFFECT2_MAGNITUDE_EDIT = 1392;
	constexpr UINT CONTROL_ID_EFFECT2_TOTAL_COST_STATIC = 1288;
	constexpr UINT CONTROL_ID_EFFECT3_COST_STATIC = 1302;
	constexpr UINT CONTROL_ID_EFFECT3_DURATION_EDIT = 1265;
	constexpr UINT CONTROL_ID_EFFECT3_EFFECT_COMBO = 1367;
	constexpr UINT CONTROL_ID_EFFECT3_EFFECT_VAR_COMBO = 1626;
	constexpr UINT CONTROL_ID_EFFECT3_MAGNITUDE_EDIT = 1393;
	constexpr UINT CONTROL_ID_EFFECT3_TOTAL_COST_STATIC = 1289;
	constexpr UINT CONTROL_ID_EFFECT4_COST_STATIC = 1303;
	constexpr UINT CONTROL_ID_EFFECT4_DURATION_EDIT = 1266;
	constexpr UINT CONTROL_ID_EFFECT4_EFFECT_COMBO = 1368;
	constexpr UINT CONTROL_ID_EFFECT4_EFFECT_VAR_COMBO = 1627;
	constexpr UINT CONTROL_ID_EFFECT4_MAGNITUDE_EDIT = 1394;
	constexpr UINT CONTROL_ID_EFFECT4_TOTAL_COST_STATIC = 1290;
	constexpr UINT CONTROL_ID_EFFECT5_COST_STATIC = 1304;
	constexpr UINT CONTROL_ID_EFFECT5_DURATION_EDIT = 1267;
	constexpr UINT CONTROL_ID_EFFECT5_EFFECT_COMBO = 1369;
	constexpr UINT CONTROL_ID_EFFECT5_EFFECT_VAR_COMBO = 1628;
	constexpr UINT CONTROL_ID_EFFECT5_MAGNITUDE_EDIT = 1395;
	constexpr UINT CONTROL_ID_EFFECT5_TOTAL_COST_STATIC = 1291;
	constexpr UINT CONTROL_ID_EFFECT6_COST_STATIC = 1305;
	constexpr UINT CONTROL_ID_EFFECT6_DURATION_EDIT = 1268;
	constexpr UINT CONTROL_ID_EFFECT6_EFFECT_COMBO = 1370;
	constexpr UINT CONTROL_ID_EFFECT6_EFFECT_VAR_COMBO = 1629;
	constexpr UINT CONTROL_ID_EFFECT6_MAGNITUDE_EDIT = 1396;
	constexpr UINT CONTROL_ID_EFFECT6_TOTAL_COST_STATIC = 1292;
	constexpr UINT CONTROL_ID_EFFECT7_COST_STATIC = 1306;
	constexpr UINT CONTROL_ID_EFFECT7_DURATION_EDIT = 1269;
	constexpr UINT CONTROL_ID_EFFECT7_EFFECT_COMBO = 1371;
	constexpr UINT CONTROL_ID_EFFECT7_EFFECT_VAR_COMBO = 1630;
	constexpr UINT CONTROL_ID_EFFECT7_MAGNITUDE_EDIT = 1397;
	constexpr UINT CONTROL_ID_EFFECT7_TOTAL_COST_STATIC = 1293;
	constexpr UINT CONTROL_ID_EFFECT8_COST_STATIC = 1307;
	constexpr UINT CONTROL_ID_EFFECT8_DURATION_EDIT = 1270;
	constexpr UINT CONTROL_ID_EFFECT8_EFFECT_COMBO = 1372;
	constexpr UINT CONTROL_ID_EFFECT8_EFFECT_VAR_COMBO = 1631;
	constexpr UINT CONTROL_ID_EFFECT8_MAGNITUDE_EDIT = 1398;
	constexpr UINT CONTROL_ID_EFFECT8_TOTAL_COST_STATIC = 1294;
	constexpr UINT CONTROL_ID_ICON_BUTTON = 1058;
	constexpr UINT CONTROL_ID_ICON_STATIC = 1120;
	constexpr UINT CONTROL_ID_ID_EDIT = 1028;
	constexpr UINT CONTROL_ID_INVENTORY_IMAGE_BUTTON = 1044;
	constexpr UINT CONTROL_ID_NAME_EDIT = 1060;
	constexpr UINT CONTROL_ID_OK_BUTTON = 1;
	constexpr UINT CONTROL_ID_REFERENCES_PERSIST_BUTTON = 1683;
	constexpr UINT CONTROL_ID_RESULTS_BUTTON = -1;
	constexpr UINT CONTROL_ID_SCRIPT_COMBO = 1226;
	constexpr UINT CONTROL_ID_SCRIPT_EDIT_BUTTON = 1062;
	constexpr UINT CONTROL_ID_VALUE_EDIT = 1084;
	constexpr UINT CONTROL_ID_WEIGHT_EDIT = 1478;

	void installPatches();
}
