-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- This table contains the semantic version of the installed MGE XE. To get it use `mge.getVersion()`.
--- @class mgeVersionTable
--- @field major integer The major version.
--- @field minor integer The minor version.
--- @field patch integer The patch version.
