-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- The data passed to callback function registered with [`mwse.overrideScript`](https://mwse.github.io/MWSE/apis/mwse/#mwseoverridescript).
--- @class mwseOverrideScriptCallbackData
--- @field reference tes3reference|nil The reference of the script. Not every script has a target reference. For example, some global scripts don't have a reference.
--- @field script tes3script The overriden script.
--- @field scriptData tes3scriptVariables No description yet available.
