-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- The data passed to callback function registered to a mwseTimer.
--- @class mwseTimerCallbackData
--- @field timer mwseTimer *Read-only*. Access to the timer that manages for this callback function. Can be used to cancel the timer inside the callback function or to access the data table stored on the timer.
