-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- A node that alters the behaviour of scene graph accumulators for its subtree. There is an additional group sorting mode added by MWSE.
--- @class niSortAdjustNode : niNode, niAVObject, niObjectNET, niObject
--- @field accumulator niAccumulator|nil An optional accumulator used by the mode ni.sortAdjustMode.subsort.
--- @field sortingMode integer The sorting mode for the subtree. There is an additional group sorting mode added by MWSE. Maps to values in the [`ni.sortAdjustMode`](https://mwse.github.io/MWSE/references/ni/sort-adjust-modes/) table.
