-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- Layout for the table passed to tooltip callback function of buttons in menu created with `tes3ui.showMessageMenu` function.
--- @class tes3ui.showMessageMenu.params.tooltip.callbackData
--- @field button tes3ui.showMessageMenu.params.button The button table of the button this tooltip was created over.
--- @field data tes3ui.showMessageMenu.params The table passed to `tes3ui.showMessageMenu` when this menu was created.
--- @field tooltip tes3uiElement The actual ui element for the tooltip.
