-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- A core game object used for storing camera objects.
--- @class tes3worldControllerRenderCamera
--- @field cameraData tes3worldControllerRenderCameraData *Read-only*. The additional data of the camera.
--- @field cameraRoot niBillboardNode|niCollisionSwitch|niNode|niSortAdjustNode|niSwitchNode *Read-only*. The root scene node of the camera.
--- @field renderer niRenderer *Read-only*. The renderer of the camera.
--- @field root niBillboardNode|niCollisionSwitch|niNode|niSortAdjustNode|niSwitchNode *Read-only*. 
