return {
	unknown = 0,
	clickAnswer = 1,
	clickTopic = 2,
	clickTopicFallback = 3,
	greeting = 4,
	hyperlinkParser = 5,
	persuasion = 6,
	script = 7,
	serviceBarter = 8,
	serviceEnchanting = 9,
	serviceRepair = 10,
	serviceSpellmaking = 11,
	serviceSpells = 12,
	serviceTraining = 13,
	serviceTravel = 14,
	topicPopulation = 15,
	voice = 16,
}
